'use client';

import React, { useEffect, useRef } from 'react';
import { ShieldCheck, MessageSquare, FolderUp, Terminal, StickyNote, Settings, Sparkles } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Card from '@/components/ui/card';
import Button from '@/components/ui/button';
import Link from 'next/link';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

export default function FeaturesPage() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const isMobile = typeof window !== 'undefined' && window.matchMedia('(max-width: 768px)').matches;
    if (isMobile) return;

    const ctx = gsap.context(() => {
      // Title entrance
      gsap.from('.gsap-title', {
        y: -30,
        opacity: 0,
        duration: 0.6,
        ease: 'power2.out'
      });

      // Cards stagger animation on scroll
      gsap.from('.gsap-card', {
        y: 60,
        opacity: 0,
        duration: 0.8,
        stagger: 0.1,
        ease: 'back.out(1.5)',
        scrollTrigger: {
          trigger: '.gsap-grid',
          start: 'top 85%'
        }
      });
    }, containerRef);

    return () => ctx.revert();
  }, []);

  const featureItems = [
    {
      title: "6-Digit Pin Join",
      description: "No emails, usernames, or signups. Just input a simple 6-digit PIN generated by the room creator and enter instantly.",
      icon: <Sparkles className="w-6 h-6 text-neo-dark" />,
      color: "white" as const,
      badge: "Fast Entry"
    },
    {
      title: "Wait-to-Join Knocking",
      description: "Secure workspace gatekeeping. Guests wait in a custom waiting room overlay until the host accepts them from their dashboard.",
      icon: <ShieldCheck className="w-6 h-6 text-neo-dark" />,
      color: "yellow" as const,
      badge: "Security"
    },
    {
      title: "Real-time Text Chat",
      description: "Playful Neo-Brutalist dialogue card interfaces. Your own messages align dynamically to the right with tail bubbles, WhatsApp style.",
      icon: <MessageSquare className="w-6 h-6 text-white" />,
      color: "purple" as const,
      badge: "Messaging"
    },
    {
      title: "Physical File Sharing",
      description: "Upload files like PDFs, presentations, slides, and images. Classmates inside the room can preview and download them instantly.",
      icon: <FolderUp className="w-6 h-6 text-neo-dark" />,
      color: "orange" as const,
      badge: "File Sharing"
    },
    {
      title: "Code Snippets Sharing",
      description: "Share formatted code snippets with classmates. Perfect for computer science lectures, lab assignments, and group projects.",
      icon: <Terminal className="w-6 h-6 text-neo-dark" />,
      color: "green" as const,
      badge: "Study Tools"
    },
    {
      title: "Collaborative Sticky Notes",
      description: "Write, update, color, or delete floating notes on a shared dashboard to collaborate on group tasks and lecture reminders.",
      icon: <StickyNote className="w-6 h-6 text-neo-dark" />,
      color: "blue" as const,
      badge: "Collaboration"
    },
    {
      title: "Host Control Panel",
      description: "Room creators keep full admin control. Mute spam messages, lock the room to new visitors, or remove unruly participants.",
      icon: <Settings className="w-6 h-6 text-neo-dark" />,
      color: "cream" as const,
      badge: "Administration"
    },
    {
      title: "Auto-Delete Timer",
      description: "Keep study materials secure. Set a timer (from 30 minutes to 24 hours) after which the room and all its content automatically delete.",
      icon: <ShieldCheck className="w-6 h-6 text-white" />,
      color: "red" as const,
      badge: "Privacy"
    }
  ];

  return (
    <div ref={containerRef} className="flex flex-col min-h-screen bg-cream selection:bg-neo-yellow selection:text-neo-dark">
      <Navbar />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20 flex flex-col gap-12 text-center">
        
        {/* Title */}
        <div className="gsap-title flex flex-col gap-3 items-center">
          <span className="bg-neo-orange text-neo-dark font-archivo text-xs uppercase tracking-wider px-3 py-1 border-[2.5px] border-neo-dark rounded-full shadow-neo-sm font-black">
            Platform Capabilities
          </span>
          <h1 className="font-archivo text-3xl sm:text-5xl uppercase text-neo-dark max-w-3xl leading-tight">
            Features Packed for Classrooms
          </h1>
          <p className="text-sm font-bold text-neo-dark/70 max-w-xl">
            Everything you and your classmates need to share files, code snippets, notes, and chats instantly on a secure network.
          </p>
        </div>

        {/* Features Grid */}
        <div className="gsap-grid grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-6">
          {featureItems.map((item, idx) => (
            <div key={idx} className="gsap-card">
              <Card variant={item.color} className="p-6 h-full flex flex-col gap-4 text-left border-[3px]">
                <div className="flex justify-between items-center">
                  <div className="w-12 h-12 bg-white border-[3px] border-neo-dark rounded-[12px] shadow-neo-sm flex items-center justify-center">
                    {item.icon}
                  </div>
                  <span className="text-[10px] font-black uppercase tracking-wider border-[2px] border-neo-dark px-2 py-0.5 rounded-full bg-cream text-neo-dark">
                    {item.badge}
                  </span>
                </div>
                <h3 className="font-archivo text-sm uppercase tracking-wide mt-2">
                  {item.title}
                </h3>
                <p className={`text-xs font-bold leading-normal ${
                  item.color === 'purple' || item.color === 'red' ? 'text-white/90' : 'text-neo-dark/75'
                }`}>
                  {item.description}
                </p>
              </Card>
            </div>
          ))}
        </div>

        {/* CTA Section */}
        <Card variant="yellow" className="p-8 md:p-12 border-[4px] shadow-neo mt-8 flex flex-col items-center gap-6 max-w-3xl mx-auto w-full">
          <h2 className="font-archivo text-xl sm:text-2xl uppercase text-neo-dark text-center">
            Ready to Collaborate?
          </h2>
          <p className="text-xs font-bold text-neo-dark/75 text-center max-w-lg leading-relaxed">
            Create an ephemeral room, share the PIN, and start sharing text, files, and sticky notes with your class in seconds.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Link href="/create">
              <Button variant="orange" size="lg" className="border-[3px] shadow-[3px_3px_0_0_#111111] hover:shadow-[5px_5px_0_0_#111111]">
                Create Room
              </Button>
            </Link>
            <Link href="/join">
              <Button variant="white" size="lg" className="border-[3px] shadow-[3px_3px_0_0_#111111] hover:shadow-[5px_5px_0_0_#111111]">
                Join Room
              </Button>
            </Link>
          </div>
        </Card>

      </main>
    </div>
  );
}
