'use client';

import React, { useEffect, useRef } from 'react';
import { ShieldCheck, MessageSquare, FolderUp, Terminal, StickyNote, Settings, Sparkles, Trash2 } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Card from '@/components/ui/card';
import Button from '@/components/ui/button';
import Link from 'next/link';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

export default function FeaturesPage() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const isMobile = typeof window !== 'undefined' && window.matchMedia('(max-width: 768px)').matches;
    if (isMobile) return;

    const ctx = gsap.context(() => {
      gsap.from('.gsap-title', {
        y: -30,
        opacity: 0,
        duration: 0.6,
        ease: 'power2.out'
      });

      gsap.from('.gsap-card', {
        y: 60,
        opacity: 0,
        duration: 0.8,
        stagger: 0.1,
        ease: 'back.out(1.5)',
        scrollTrigger: {
          trigger: '.gsap-grid',
          start: 'top 85%'
        }
      });
    }, containerRef);

    return () => ctx.revert();
  }, []);

  const featureItems = [
    { title: "6-Digit Pin Join", description: "No emails, usernames, or signups. Just input a simple 6-digit PIN generated by the room creator and enter instantly.", icon: <Sparkles className="w-5 h-5" />, accent: '#FFD600', badge: "Fast Entry" },
    { title: "Wait-to-Join Knocking", description: "Secure workspace gatekeeping. Guests wait in a custom waiting room overlay until the host accepts them from their dashboard.", icon: <ShieldCheck className="w-5 h-5" />, accent: '#22C55E', badge: "Security" },
    { title: "Real-time Text Chat", description: "Playful dialogue card interfaces. Your own messages align dynamically to the right with tail bubbles, WhatsApp style.", icon: <MessageSquare className="w-5 h-5" />, accent: '#8B5CF6', badge: "Messaging" },
    { title: "Physical File Sharing", description: "Upload files like PDFs, presentations, slides, and images. Classmates inside the room can preview and download them instantly.", icon: <FolderUp className="w-5 h-5" />, accent: '#FF6A00', badge: "File Sharing" },
    { title: "Code Snippets Sharing", description: "Share formatted code snippets with classmates. Perfect for computer science lectures, lab assignments, and group projects.", icon: <Terminal className="w-5 h-5" />, accent: '#4F7CFF', badge: "Study Tools" },
    { title: "Collaborative Sticky Notes", description: "Write, update, color, or delete floating notes on a shared dashboard to collaborate on group tasks and lecture reminders.", icon: <StickyNote className="w-5 h-5" />, accent: '#22C55E', badge: "Collaboration" },
    { title: "Host Control Panel", description: "Room creators keep full admin control. Mute spam messages, lock the room to new visitors, or remove unruly participants.", icon: <Settings className="w-5 h-5" />, accent: '#a1a1aa', badge: "Administration" },
    { title: "Auto-Delete Timer", description: "Keep study materials secure. Set a timer (from 30 minutes to 24 hours) after which the room and all its content automatically delete.", icon: <Trash2 className="w-5 h-5" />, accent: '#EF4444', badge: "Privacy" }
  ];

  return (
    <div ref={containerRef} className="flex flex-col min-h-screen bg-[#050608] text-[#f4f4f5]">
      <Navbar />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20 flex flex-col gap-12 text-center relative z-10">
        
        {/* Title */}
        <div className="gsap-title flex flex-col gap-3 items-center">
          <span className="bg-[#FF6A00]/15 text-[#FF6A00] border border-[#FF6A00]/25 text-xs font-medium px-3.5 py-1.5 rounded-full animate-pulse">
            Platform Capabilities
          </span>
          <h1 className="text-3xl sm:text-5xl font-bold text-[#f4f4f5] max-w-3xl leading-tight">
            Features Packed for Classrooms
          </h1>
          <p className="text-sm text-[#71717a] max-w-xl">
            Everything you and your classmates need to share files, code snippets, notes, and chats instantly on a secure network.
          </p>
        </div>

        {/* Features Grid */}
        <div className="gsap-grid grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6">
          {featureItems.map((item, idx) => (
            <div key={idx} className="gsap-card">
              <div 
                className="glow-card p-5 h-full flex flex-col gap-4 text-left cursor-pointer transition-all duration-300"
                style={{ '--glow-color': item.accent } as React.CSSProperties}
              >
                <div className="flex justify-between items-center">
                  <div 
                    className="w-10 h-10 rounded-xl flex items-center justify-center"
                    style={{ background: `${item.accent}15`, border: `1px solid ${item.accent}25`, color: item.accent }}
                  >
                    {item.icon}
                  </div>
                  <span 
                    className="text-[10px] font-medium px-2 py-0.5 rounded-full border"
                    style={{ color: item.accent, borderColor: `${item.accent}25`, background: `${item.accent}10` }}
                  >
                    {item.badge}
                  </span>
                </div>
                <h3 className="text-sm font-semibold text-[#f4f4f5] mt-2">
                  {item.title}
                </h3>
                <p className="text-xs text-[#71717a] leading-relaxed">
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Call to Action */}
        <div className="mt-8 flex justify-center">
          <Link href="/create">
            <Button variant="yellow" size="lg" className="shadow-[0_0_20px_rgba(255,214,0,0.2)]">
              Create a Room
            </Button>
          </Link>
        </div>

      </main>
    </div>
  );
}
