'use client';

import React, { useEffect, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { 
  Zap, Shield, Sparkles, Folder, Code, FileText, Trash2, ArrowRight,
  ShieldCheck, FolderUp, Terminal, StickyNote, Settings,
  PlusCircle, Share2, Users, Flame, Check, ShieldAlert,
  Compass, Target, GraduationCap, BookOpen, MessageSquare
} from 'lucide-react';
import Button from '@/components/ui/button';
import Card from '@/components/ui/card';
import Navbar from '@/components/Navbar';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

const RollingDigit = ({ value, baseAngle }: { value: number; baseAngle: number }) => {
  return (
    <motion.div 
      animate={{ 
        rotate: value % 2 === 0 
          ? [baseAngle, baseAngle - 6, baseAngle] 
          : [baseAngle, baseAngle + 6, baseAngle]
      }}
      transition={{ type: "spring", stiffness: 100, damping: 8 }}
      className="w-10 h-12 border-[3px] border-neo-dark rounded-[8px] bg-white overflow-hidden shadow-neo-sm relative flex justify-center"
      style={{ transform: `rotate(${baseAngle}deg)` }}
    >
      <motion.div
        animate={{ y: -value * 42 }}
        transition={{ type: "spring", stiffness: 45, damping: 10 }}
        className="flex flex-col items-center w-full absolute top-0"
      >
        {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((num) => (
          <span 
            key={num} 
            className="w-full flex items-center justify-center font-archivo text-lg sm:text-xl font-black text-neo-dark select-none"
            style={{ height: '42px', lineHeight: '42px' }}
          >
            {num}
          </span>
        ))}
      </motion.div>
    </motion.div>
  );
};

export default function LandingPage() {
  const pageContainerRef = useRef<HTMLDivElement>(null);
  const [pinDigits, setPinDigits] = React.useState<number[]>([4, 0, 8, 2, 1, 5]);

  useEffect(() => {
    const interval = setInterval(() => {
      setPinDigits([
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
      ]);
    }, 2800);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const isMobile = typeof window !== 'undefined' && window.matchMedia('(max-width: 768px)').matches;
    if (isMobile) return;

    const ctx = gsap.context(() => {
      // 1. Features Grid Animation (play reverse play reverse)
      gsap.from('.gsap-feature-card', {
        y: 60,
        opacity: 0,
        duration: 0.8,
        stagger: 0.1,
        ease: 'back.out(1.5)',
        scrollTrigger: {
          trigger: '.gsap-feature-grid',
          start: 'top 85%',
          end: 'bottom 15%',
          toggleActions: 'play reverse play reverse'
        }
      });

      // 2. How It Works Steps timeline
      gsap.utils.toArray('.gsap-step-card').forEach((step: any, index) => {
        const isEven = index % 2 === 0;
        gsap.from(step, {
          x: isEven ? -100 : 100,
          opacity: 0,
          duration: 0.8,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: step,
            start: 'top 85%',
            end: 'bottom 15%',
            toggleActions: 'play reverse play reverse'
          }
        });
      });


      // 4. About Story Card Slide In
      gsap.from('.gsap-about-story', {
        scale: 0.96,
        opacity: 0,
        duration: 0.8,
        ease: 'power2.out',
        scrollTrigger: {
          trigger: '.gsap-about-story',
          start: 'top 85%',
          end: 'bottom 15%',
          toggleActions: 'play reverse play reverse'
        }
      });

      // 5. About Values Cards Stagger
      gsap.from('.gsap-about-value', {
        y: 50,
        opacity: 0,
        duration: 0.8,
        stagger: 0.15,
        ease: 'back.out(1.5)',
        scrollTrigger: {
          trigger: '.gsap-about-values-grid',
          start: 'top 85%',
          end: 'bottom 15%',
          toggleActions: 'play reverse play reverse'
        }
      });
    }, pageContainerRef);

    return () => ctx.revert();
  }, []);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  } as const;

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { type: 'spring', stiffness: 100 } }
  } as const;

  const featureItems = [
    {
      title: "6-Digit Pin Join",
      description: "No emails, usernames, or signups. Just input a simple 6-digit PIN generated by the room creator and enter instantly.",
      icon: <Sparkles className="w-5 h-5 text-neo-dark" />,
      color: "white" as const,
      badge: "Fast Entry"
    },
    {
      title: "Wait-to-Join Knocking",
      description: "Secure workspace gatekeeping. Guests wait in a custom waiting room overlay until the host accepts them from their dashboard.",
      icon: <ShieldCheck className="w-5 h-5 text-neo-dark" />,
      color: "yellow" as const,
      badge: "Security"
    },
    {
      title: "Real-time Text Chat",
      description: "Playful Neo-Brutalist dialogue card interfaces. Your own messages align dynamically to the right with tail bubbles, WhatsApp style.",
      icon: <MessageSquare className="w-5 h-5 text-white" />,
      color: "purple" as const,
      badge: "Messaging"
    },
    {
      title: "Physical File Sharing",
      description: "Upload files like PDFs, presentations, slides, and images. Classmates inside the room can preview and download them instantly.",
      icon: <FolderUp className="w-5 h-5 text-neo-dark" />,
      color: "orange" as const,
      badge: "File Sharing"
    },
    {
      title: "Code Snippets Sharing",
      description: "Share formatted code snippets with classmates. Perfect for computer science lectures, lab assignments, and group projects.",
      icon: <Terminal className="w-5 h-5 text-neo-dark" />,
      color: "green" as const,
      badge: "Study Tools"
    },
    {
      title: "Collaborative Sticky Notes",
      description: "Write, update, color, or delete floating notes on a shared dashboard to collaborate on group tasks and lecture reminders.",
      icon: <StickyNote className="w-5 h-5 text-neo-dark" />,
      color: "blue" as const,
      badge: "Collaboration"
    },
    {
      title: "Host Control Panel",
      description: "Room creators keep full admin control. Mute spam messages, lock the room to new visitors, or remove unruly participants.",
      icon: <Settings className="w-5 h-5 text-neo-dark" />,
      color: "cream" as const,
      badge: "Administration"
    },
    {
      title: "Auto-Delete Timer",
      description: "Keep study materials secure. Set a timer (from 30 minutes to 24 hours) after which the room and all its content automatically delete.",
      icon: <ShieldCheck className="w-5 h-5 text-white" />,
      color: "red" as const,
      badge: "Privacy"
    }
  ];

  const steps = [
    {
      number: "01",
      title: "Create a Room",
      description: "Hit the 'Create Room' button. Choose a name for your workspace, set the max participant limit (up to 100 members), and configure an auto-delete self-destruct timer (from 30 minutes up to 24 hours). We will instantly spawn a room PIN in the database.",
      icon: <PlusCircle className="w-8 h-8 text-neo-dark" />,
      color: "white" as const,
      colorTag: "bg-neo-yellow"
    },
    {
      number: "02",
      title: "Share the Credentials",
      description: "Copy the 6-digit room PIN. Share it with your friends, classmates, or project buddies. There are no registration links or passwords; they just need the PIN to connect.",
      icon: <Share2 className="w-8 h-8 text-neo-dark" />,
      color: "cream" as const,
      colorTag: "bg-neo-orange"
    },
    {
      number: "03",
      title: "Approve & Collaborate",
      description: "As the host, you receive a floating entry notification when buddies knock to join. Click 'Accept' to let them enter. Once inside, everyone can upload physical files, write text chat messages, share C++/JS snippets, and organize sticky notes on a shared wall.",
      icon: <Users className="w-8 h-8 text-white" />,
      color: "purple" as const,
      colorTag: "bg-white text-neo-dark"
    },
    {
      number: "04",
      title: "Automatic Self-Destruct",
      description: "Keep your details completely private. As soon as the host's configured countdown timer expires, the server triggers an automated scrub. The room status changes to 'Expired', clearing the chat feed, physical files, sticky notes, and room history from memory.",
      icon: <Flame className="w-8 h-8 text-neo-dark" />,
      color: "white" as const,
      colorTag: "bg-neo-red text-white"
    }
  ];



  const values = [
    {
      title: "Zero-Friction Access",
      desc: "Collaboration should start instantly. We cut out registration walls, authentication screens, and emails. Enter a study room in two clicks.",
      icon: <Compass className="w-8 h-8 text-neo-dark" />,
      color: "white" as const
    },
    {
      title: "Privacy by Design",
      desc: "We don't sell your data. Files shared are ephemeral. Rooms, logs, chats, and documents self-destruct from the servers as soon as your timer completes.",
      icon: <Target className="w-8 h-8 text-neo-dark" />,
      color: "cream" as const
    },
    {
      title: "Built for Students",
      desc: "Built for labs, study grids, hackathons, and lectures. Simple features tailored specifically to code compiling, PDF reviewing, and exam note mapping.",
      icon: <GraduationCap className="w-8 h-8 text-white" />,
      color: "purple" as const
    }
  ];

  return (
    <div ref={pageContainerRef} className="flex flex-col min-h-screen bg-cream selection:bg-neo-yellow selection:text-neo-dark scroll-smooth overflow-x-hidden">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Lab Buddies",
            "description": "Lab Buddies is a secure, no login temporary study room workspace for students. Share files, code snippets, notes, and links instantly using a simple 6-digit room PIN.",
            "applicationCategory": "EducationalApplication",
            "operatingSystem": "All",
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            }
          })
        }}
      />
      <Navbar />

      {/* Main Content Area */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20 flex flex-col gap-28">
        
        {/* Section 0: Hero Section */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          {/* Left Column - Headline & Call to Action */}
          <div className="lg:col-span-7 flex flex-col gap-6 text-left">
            <motion.div 
              variants={containerVariants}
              initial="hidden"
              animate="visible"
              className="flex flex-col gap-6"
            >
              <motion.div variants={itemVariants} className="inline-flex items-center gap-1.5 self-start bg-neo-purple text-white px-3 py-1 border-[2.5px] border-neo-dark rounded-full text-xs font-black uppercase tracking-wider shadow-neo-sm">
                <Sparkles className="w-3.5 h-3.5 fill-white" />
                <span>#1 Platform for Students</span>
              </motion.div>

              <motion.h1 variants={itemVariants} className="font-archivo text-4xl sm:text-5xl lg:text-6xl leading-[1.05] tracking-tight uppercase text-neo-dark">
                Share Code.<br />
                Share Files.<br />
                <span className="text-neo-orange">No Login Required.</span>
              </motion.h1>

              <motion.p variants={itemVariants} className="text-base sm:text-lg font-semibold text-neo-dark/80 max-w-xl">
                Instantly share code snippets, notes, files, terminal outputs and links with classmates using a simple 6-digit room PIN.
              </motion.p>

              {/* Action Buttons */}
              <motion.div variants={itemVariants} className="flex flex-wrap gap-4 mt-2">
                <Link href="/create">
                  <Button variant="yellow" size="lg" className="gap-2 group">
                    <span>Create Room</span>
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
                <Link href="/join">
                  <Button variant="white" size="lg">
                    Join Room
                  </Button>
                </Link>
              </motion.div>

              {/* SEO Value Proposition */}
              <motion.div variants={itemVariants} className="flex items-center gap-2 mt-4 select-none">
                <div className="bg-neo-yellow text-neo-dark font-archivo text-xs px-3 py-1 border-[2.5px] border-neo-dark rounded shadow-neo-sm font-black">
                  No login. No tracking. Just a PIN.
                </div>
              </motion.div>
            </motion.div>
          </div>

          {/* Right Column - Conceptual Neo-Brutalist Illustration */}
          <div className="lg:col-span-5 flex justify-center relative">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ type: 'spring', stiffness: 80, delay: 0.3 }}
              className="relative w-full max-w-[420px] aspect-square flex items-center justify-center"
            >
              {/* Decorative background shapes */}
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[320px] h-[320px] rounded-full border-[3px] border-dashed border-neo-dark/30 animate-spin" style={{ animationDuration: '60s' }} />
              <div className="absolute -bottom-4 -right-4 w-32 h-32 bg-neo-yellow rounded-full border-[3px] border-neo-dark -z-10 shadow-neo" />
              <div className="absolute -top-6 -left-6 w-16 h-16 bg-neo-blue rounded-lg border-[3px] border-neo-dark rotate-12 -z-10" />

              {/* Main Laptop Illustration Container */}
              <div className="relative z-10 w-full flex flex-col gap-6 items-center">
                {/* Upper row items: Laptop (Code) and Folder */}
                <div className="flex justify-between w-full px-4 items-end">
                  {/* Laptop Card */}
                  <Card variant="white" hasShadow shadowSize="sm" className="p-3 w-32 rotate-[-6deg] hover:rotate-0 transition-transform">
                    <div className="bg-neo-yellow p-2 border-[2px] border-neo-dark rounded-lg flex items-center justify-center mb-2">
                      <Code className="w-6 h-6 text-neo-dark" />
                    </div>
                    <div className="h-1.5 w-16 bg-neo-dark rounded-full mb-1"></div>
                    <div className="h-1.5 w-12 bg-neo-dark/50 rounded-full"></div>
                  </Card>

                  {/* Folder Card */}
                  <Card variant="orange" hasShadow shadowSize="sm" className="p-3 w-28 rotate-[8deg] hover:rotate-0 transition-transform text-neo-dark">
                    <Folder className="w-10 h-10 fill-neo-dark mb-1" />
                    <div className="h-1.5 w-10 bg-neo-dark rounded-full"></div>
                  </Card>
                </div>

                {/* Center Row: 6-Digit Room Pin */}
                <div className="flex flex-col items-center gap-2">
                  <span className="font-archivo text-xs uppercase tracking-wider text-neo-dark bg-white border-[2px] border-neo-dark px-3 py-1 rounded-md shadow-neo-sm font-black">
                    Room PIN
                  </span>
                  <div className="flex gap-1.5">
                    {pinDigits.map((digit, idx) => (
                      <RollingDigit 
                        key={idx} 
                        value={digit} 
                        baseAngle={(idx - 2.5) * 3} 
                      />
                    ))}
                  </div>
                </div>

                {/* Lower Row items: Notes and Devices */}
                <div className="flex justify-between w-full px-4 items-start">
                  {/* Notes Card */}
                  <Card variant="purple" hasShadow shadowSize="sm" className="p-3 w-28 rotate-[-12deg] hover:rotate-0 transition-transform">
                    <FileText className="w-8 h-8 text-white mb-2" />
                    <div className="h-1.5 w-12 bg-white rounded-full mb-1"></div>
                    <div className="h-1.5 w-8 bg-white/60 rounded-full"></div>
                  </Card>

                  {/* Desktop / Green device Card */}
                  <Card variant="green" hasShadow shadowSize="sm" className="p-3 w-32 rotate-[6deg] hover:rotate-0 transition-transform">
                    <div className="bg-white border-[2px] border-neo-dark h-12 rounded flex items-center justify-center mb-1 font-archivo text-xs font-black">
                      ACTIVE
                    </div>
                    <div className="h-2 w-14 bg-neo-dark rounded-full"></div>
                  </Card>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Section 1: Features Section */}
        <section id="features" className="flex flex-col gap-10 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="bg-neo-orange text-neo-dark font-archivo text-xs uppercase tracking-wider px-3 py-1 border-[2.5px] border-neo-dark rounded-full shadow-neo-sm font-black select-none">
              Platform Capabilities
            </span>
            <h2 className="font-archivo text-2xl sm:text-4xl uppercase text-neo-dark max-w-2xl leading-tight">
              Features Packed for Classrooms
            </h2>
            <p className="text-xs sm:text-sm font-bold text-neo-dark/70 max-w-md">
              Everything you and your classmates need to share files, code snippets, notes, and chats instantly on a secure local network.
            </p>
          </div>

          <div className="gsap-feature-grid grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {featureItems.map((item, idx) => (
              <div key={idx} className="gsap-feature-card">
                <Card variant={item.color} className="p-6 h-full flex flex-col gap-4 text-left border-[3px] shadow-neo-sm">
                  <div className="flex justify-between items-center">
                    <div className="w-10 h-10 bg-white border-[2.5px] border-neo-dark rounded-[10px] shadow-neo-sm flex items-center justify-center">
                      {item.icon}
                    </div>
                    <span className="text-[9px] font-black uppercase tracking-wider border-[1.5px] border-neo-dark px-2 py-0.5 rounded-full bg-cream text-neo-dark">
                      {item.badge}
                    </span>
                  </div>
                  <h3 className="font-archivo text-xs uppercase tracking-wide mt-2">
                    {item.title}
                  </h3>
                  <p className={`text-[11px] font-bold leading-normal ${
                    item.color === 'purple' || item.color === 'red' ? 'text-white/85' : 'text-neo-dark/70'
                  }`}>
                    {item.description}
                  </p>
                </Card>
              </div>
            ))}
          </div>
        </section>

        {/* Section 2: How It Works Section */}
        <section id="how-it-works" className="flex flex-col gap-10 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="bg-neo-blue text-white font-archivo text-xs uppercase tracking-wider px-3 py-1 border-[2.5px] border-neo-dark rounded-full shadow-neo-sm font-black select-none">
              System Guide
            </span>
            <h2 className="font-archivo text-2xl sm:text-4xl uppercase text-neo-dark max-w-2xl leading-tight">
              How Lab Buddies Works
            </h2>
            <p className="text-xs sm:text-sm font-bold text-neo-dark/70 max-w-md">
              A secure, zero-friction path to temporary student collaborations. Learn how we handle rooms in 4 simple steps.
            </p>
          </div>

          <div className="flex flex-col gap-6 max-w-4xl mx-auto w-full">
            {steps.map((step, idx) => (
              <div key={idx} className="gsap-step-card">
                <Card variant={step.color} className="p-5 md:p-6 border-[3px] shadow-neo-sm hover:shadow-neo transition-all">
                  <div className="flex flex-col md:flex-row gap-5 items-start md:items-center">
                    {/* Number Badge */}
                    <div className={`w-12 h-12 rounded-full border-[2.5px] border-neo-dark flex items-center justify-center font-archivo text-lg font-black flex-shrink-0 shadow-neo-sm ${step.colorTag}`}>
                      {step.number}
                    </div>
                    {/* Text Body */}
                    <div className="flex-1 flex flex-col gap-1.5 text-left">
                      <h3 className="font-archivo text-sm uppercase text-neo-dark tracking-wide flex items-center gap-2">
                        <span className="scale-75">{step.icon}</span>
                        {step.title}
                      </h3>
                      <p className={`text-[11px] font-semibold leading-relaxed ${
                        step.color === 'purple' ? 'text-white/85' : 'text-neo-dark/70'
                      }`}>
                        {step.description}
                      </p>
                    </div>
                  </div>
                </Card>
              </div>
            ))}
          </div>
        </section>


        {/* Section 4: About Us Section */}
        <section id="about" className="flex flex-col gap-10 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="bg-neo-purple text-white font-archivo text-xs uppercase tracking-wider px-3 py-1 border-[2.5px] border-neo-dark rounded-full shadow-neo-sm font-black select-none">
              Our Mission
            </span>
            <h2 className="font-archivo text-2xl sm:text-4xl uppercase text-neo-dark max-w-2xl leading-tight">
              Designed to Connect Classmates
            </h2>
            <p className="text-xs sm:text-sm font-bold text-neo-dark/70 max-w-md">
              We believe study resources should be shared instantly, privately, and seamlessly. Learn what drives our product.
            </p>
          </div>

          <div className="flex flex-col gap-8 max-w-4xl mx-auto w-full">
            {/* Story Card */}
            <div className="gsap-about-story">
              <Card variant="white" className="p-6 md:p-8 text-left border-[3px] shadow-neo flex flex-col gap-4">
                <div className="flex items-center gap-2 border-b-[2.5px] border-neo-dark pb-2.5 select-none">
                  <BookOpen className="w-5 h-5 text-neo-orange" />
                  <h3 className="font-archivo text-sm uppercase text-neo-dark tracking-wide">
                    The Story behind "Lab Buddies"
                  </h3>
                </div>
                <div className="flex flex-col gap-3.5 text-xs font-semibold text-neo-dark/75 leading-relaxed">
                  <p>
                    During computer lab lectures and group study sessions, sharing code scripts, PDF slides, and terminal stack outputs was incredibly frustrating. Emailing files felt archaic, setting up GitHub repos for simple debugging code took too much time, and using common messaging boards leaked personal emails or phone numbers.
                  </p>
                  <p>
                    We designed <strong>Lab Buddies</strong> to solve this exact bottleneck. It is a lightweight, zero-configuration study room workspace where anyone can launch a collaboration session under a 6-digit PIN. 
                  </p>
                  <p>
                    By combining instant chat messaging and shared sticky notes with file sharing and code helpers, we created the ultimate lightweight study room for students. 
                  </p>
                </div>
              </Card>
            </div>

            {/* Core Values grid */}
            <div className="gsap-about-values-grid grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
              {values.map((val, idx) => (
                <div key={idx} className="gsap-about-value flex h-full">
                  <Card variant={val.color} className="p-5 border-[3px] shadow-neo-sm h-full flex flex-col gap-3">
                    <div className="w-10 h-10 bg-white border-[2px] border-neo-dark rounded-[10px] shadow-neo-sm flex items-center justify-center flex-shrink-0">
                      {val.icon}
                    </div>
                    <h4 className="font-archivo text-xs uppercase tracking-wide mt-1">
                      {val.title}
                    </h4>
                    <p className={`text-[11px] font-semibold leading-relaxed ${
                      val.color === 'purple' ? 'text-white/80' : 'text-neo-dark/70'
                    }`}>
                      {val.desc}
                    </p>
                  </Card>
                </div>
              ))}
            </div>
          </div>
        </section>

      </main>

      <footer className="border-t-[3px] border-neo-dark bg-white py-6 mt-auto select-none">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 font-archivo text-xs uppercase tracking-wider text-neo-dark font-black">
          <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-6">
            <span>No Signups. No Downloads. Just Share.</span>
            <span className="hidden sm:inline text-neo-dark/30">|</span>
            <div className="flex gap-4">
              <Link href="/privacy" className="hover:text-neo-orange hover:underline transition-all text-neo-dark/70">Privacy Policy</Link>
              <Link href="/terms" className="hover:text-neo-orange hover:underline transition-all text-neo-dark/70">Terms of Service</Link>
            </div>
          </div>

          {/* Powered by Modi Studio */}
          <div className="flex items-center gap-2">
            <span className="text-[10px] text-neo-dark/50">Powered by</span>
            <a 
              href="https://modistudio.online" 
              target="_blank" 
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 bg-neo-dark text-white rounded-full pl-1 pr-3 py-1 shadow-neo-sm hover:translate-y-[-1px] transition-all cursor-pointer select-none active:translate-y-0 active:shadow-neo-sm"
            >
              <Image 
                src="/modi-studio-logo.jpg" 
                alt="Modi Studio logo - publisher and developer of Lab Buddies" 
                width={20}
                height={20}
                className="w-5 h-5 rounded-full object-cover border border-white/20" 
              />
              <span className="font-archivo text-[9.5px] uppercase font-black tracking-wide text-white">
                Modi Studio
              </span>
            </a>
          </div>

          <div className="flex items-center gap-1.5 text-neo-green">
            <Shield className="w-4 h-4 text-neo-green fill-neo-green/10" />
            <span>100% Private</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
