'use client';

import React, { useEffect, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'framer-motion';
import {
  Zap, Shield, Sparkles, Folder, Code, FileText, Trash2, ArrowRight,
  ShieldCheck, FolderUp, Terminal, StickyNote, Settings,
  PlusCircle, Share2, Users, Flame, Check, ShieldAlert,
  Compass, Target, GraduationCap, BookOpen, MessageSquare, Lock
} from 'lucide-react';
import Button from '@/components/ui/button';
import Card from '@/components/ui/card';
import Navbar from '@/components/Navbar';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

const RollingDigit = ({ value, baseAngle }: { value: number; baseAngle: number }) => {
  return (
    <motion.div
      animate={{
        rotate: value % 2 === 0
          ? [baseAngle, baseAngle - 6, baseAngle]
          : [baseAngle, baseAngle + 6, baseAngle]
      }}
      transition={{ type: "tween", ease: "easeInOut", duration: 0.5 }}
      className="w-10 h-12 border border-[#FFD600]/30 rounded-xl bg-[#FFD600]/10 overflow-hidden relative flex justify-center shadow-[0_0_12px_rgba(255,214,0,0.15)]"
      style={{ transform: `rotate(${baseAngle}deg)` }}
    >
      <motion.div
        animate={{ y: -value * 42 }}
        transition={{ type: "spring", stiffness: 45, damping: 10 }}
        className="flex flex-col items-center w-full absolute top-0"
      >
        {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((num) => (
          <span
            key={num}
            className="w-full flex items-center justify-center text-lg sm:text-xl font-bold text-[#FFD600] select-none font-mono"
            style={{ height: '42px', lineHeight: '42px' }}
          >
            {num}
          </span>
        ))}
      </motion.div>
    </motion.div>
  );
};

export default function LandingPage() {
  const pageContainerRef = useRef<HTMLDivElement>(null);
  const [pinDigits, setPinDigits] = React.useState<number[]>([4, 0, 8, 2, 1, 5]);

  useEffect(() => {
    const interval = setInterval(() => {
      setPinDigits([
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
      ]);
    }, 2800);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const isMobile = typeof window !== 'undefined' && window.matchMedia('(max-width: 768px)').matches;
    if (isMobile) return;

    const ctx = gsap.context(() => {
      gsap.from('.gsap-feature-card', {
        y: 60, opacity: 0, duration: 0.8, stagger: 0.1, ease: 'back.out(1.5)',
        scrollTrigger: { trigger: '.gsap-feature-grid', start: 'top 85%', end: 'bottom 15%', toggleActions: 'play reverse play reverse' }
      });
      gsap.utils.toArray('.gsap-step-card').forEach((step: any, index) => {
        const isEven = index % 2 === 0;
        gsap.from(step, {
          x: isEven ? -100 : 100, opacity: 0, duration: 0.8, ease: 'power3.out',
          scrollTrigger: { trigger: step, start: 'top 85%', end: 'bottom 15%', toggleActions: 'play reverse play reverse' }
        });
      });
      gsap.from('.gsap-about-story', {
        scale: 0.96, opacity: 0, duration: 0.8, ease: 'power2.out',
        scrollTrigger: { trigger: '.gsap-about-story', start: 'top 85%', end: 'bottom 15%', toggleActions: 'play reverse play reverse' }
      });
      gsap.from('.gsap-about-value', {
        y: 50, opacity: 0, duration: 0.8, stagger: 0.15, ease: 'back.out(1.5)',
        scrollTrigger: { trigger: '.gsap-about-values-grid', start: 'top 85%', end: 'bottom 15%', toggleActions: 'play reverse play reverse' }
      });
    }, pageContainerRef);
    return () => ctx.revert();
  }, []);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  } as const;

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { type: 'spring', stiffness: 100 } }
  } as const;

  const featureItems = [
    { title: "6-Digit Pin Join", description: "No emails, usernames, or signups. Just input a simple 6-digit PIN generated by the room creator and enter instantly.", icon: <Sparkles className="w-5 h-5" />, accent: '#FFD600', badge: "Fast Entry" },
    { title: "Wait-to-Join Knocking", description: "Secure workspace gatekeeping. Guests wait in a custom waiting room overlay until the host accepts them from their dashboard.", icon: <ShieldCheck className="w-5 h-5" />, accent: '#22C55E', badge: "Security" },
    { title: "Real-time Text Chat", description: "Playful dialogue card interfaces. Your own messages align dynamically to the right with tail bubbles, WhatsApp style.", icon: <MessageSquare className="w-5 h-5" />, accent: '#8B5CF6', badge: "Messaging" },
    { title: "Physical File Sharing", description: "Upload files like PDFs, presentations, slides, and images. Classmates inside the room can preview and download them instantly.", icon: <FolderUp className="w-5 h-5" />, accent: '#FF6A00', badge: "File Sharing" },
    { title: "Code Snippets Sharing", description: "Share formatted code snippets with classmates. Perfect for computer science lectures, lab assignments, and group projects.", icon: <Terminal className="w-5 h-5" />, accent: '#4F7CFF', badge: "Study Tools" },
    { title: "Collaborative Sticky Notes", description: "Write, update, color, or delete floating notes on a shared dashboard to collaborate on group tasks and lecture reminders.", icon: <StickyNote className="w-5 h-5" />, accent: '#22C55E', badge: "Collaboration" },
    { title: "Host Control Panel", description: "Room creators keep full admin control. Mute spam messages, lock the room to new visitors, or remove unruly participants.", icon: <Settings className="w-5 h-5" />, accent: '#a1a1aa', badge: "Administration" },
    { title: "Auto-Delete Timer", description: "Keep study materials secure. Set a timer (from 30 minutes to 24 hours) after which the room and all its content automatically delete.", icon: <Trash2 className="w-5 h-5" />, accent: '#EF4444', badge: "Privacy" }
  ];

  const steps = [
    { number: "01", title: "Create a Room", description: "Hit the 'Create Room' button. Choose a name for your workspace, set the max participant limit (up to 100 members), and configure an auto-delete self-destruct timer (from 30 minutes up to 24 hours). We will instantly spawn a room PIN in the database.", icon: <PlusCircle className="w-6 h-6" />, accent: '#FFD600' },
    { number: "02", title: "Share the Credentials", description: "Copy the 6-digit room PIN. Share it with your friends, classmates, or project buddies. There are no registration links or passwords; they just need the PIN to connect.", icon: <Share2 className="w-6 h-6" />, accent: '#FF6A00' },
    { number: "03", title: "Approve & Collaborate", description: "As the host, you receive a floating entry notification when buddies knock to join. Click 'Accept' to let them enter. Once inside, everyone can upload physical files, write text chat messages, share code snippets, and organize sticky notes on a shared wall.", icon: <Users className="w-6 h-6" />, accent: '#8B5CF6' },
    { number: "04", title: "Automatic Self-Destruct", description: "Keep your details completely private. As soon as the host's configured countdown timer expires, the server triggers an automated scrub. The room status changes to 'Expired', clearing the chat feed, physical files, sticky notes, and room history from memory.", icon: <Flame className="w-6 h-6" />, accent: '#EF4444' }
  ];

  const values = [
    { title: "Zero-Friction Access", desc: "Collaboration should start instantly. We cut out registration walls, authentication screens, and emails. Enter a study room in two clicks.", icon: <Compass className="w-6 h-6" />, accent: '#FFD600' },
    { title: "Privacy by Design", desc: "We don't sell your data. Files shared are ephemeral. Rooms, logs, chats, and documents self-destruct from the servers as soon as your timer completes.", icon: <Target className="w-6 h-6" />, accent: '#22C55E' },
    { title: "Built for Students", desc: "Built for labs, study grids, hackathons, and lectures. Simple features tailored specifically to code compiling, PDF reviewing, and exam note mapping.", icon: <GraduationCap className="w-6 h-6" />, accent: '#8B5CF6' }
  ];

  return (
    <div ref={pageContainerRef} className="flex flex-col min-h-screen bg-[#050608] text-[#f4f4f5] scroll-smooth overflow-x-hidden">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            {
              "@context": "https://schema.org",
              "@type": "WebApplication",
              "name": "Lab Buddies",
              "url": "https://labbuddies.hariommodi.online",
              "applicationCategory": "EducationalApplication, UtilitiesApplication",
              "operatingSystem": "All",
              "description": "Free, no login temporary study room workspace for students. Share files, code snippets, notes, and links instantly using a simple 6-digit room PIN.",
              "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "4.9",
                "ratingCount": "1420",
                "bestRating": "5"
              }
            },
            {
              "@context": "https://schema.org",
              "@type": "FAQPage",
              "mainEntity": [
                {
                  "@type": "Question",
                  "name": "How does Lab Buddies compare to Snapdrop and Sharedrop?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Unlike Snapdrop and Sharedrop which strictly require both devices to be on the exact same Wi-Fi subnet, Lab Buddies connects devices instantly using a simple 6-digit Room PIN across any network or cellular connection, with code snippet formatting and collaborative notes."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Can I share files between Android, iPhone, Windows, Mac, and Linux?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes! Lab Buddies is 100% browser-based and works seamlessly as a Progressive Web App (PWA) across all modern operating systems and web browsers without downloading software."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Is there any signup, login, or personal info required?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "No. Lab Buddies requires zero logins, no emails, and no phone numbers. You can launch a workspace or join an existing study room in two clicks using just a 6-digit Room PIN."
                  }
                },
                {
                  "@type": "Question",
                  "name": "How does the auto-delete self-destruct timer protect my files and notes?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Every room has a configured self-destruct countdown timer (from 5 minutes up to 24 hours). Once the countdown expires, all shared files, code snippets, notes, and chat logs are permanently purged from the servers."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Is Lab Buddies completely free to use?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes! Lab Buddies is 100% free for students and developers to create temporary collaboration workspaces, transfer files, run lab attendance, and share formatted code snippets."
                  }
                }
              ]
            }
          ])
        }}
      />
      <Navbar />

      {/* Background radial gradient */}
      <div className="pointer-events-none fixed inset-0 z-0" style={{ background: 'radial-gradient(ellipse 80% 50% at 50% -10%, rgba(255,214,0,0.06), transparent)' }} />

      <main className="relative z-10 flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24 flex flex-col gap-32">

        {/* ── Hero Section ── */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-7 flex flex-col gap-8 text-left">
            <motion.div variants={containerVariants} initial="hidden" animate="visible" className="flex flex-col gap-6">
              <motion.div variants={itemVariants} className="inline-flex items-center gap-2 self-start bg-[#FFD600]/10 text-[#FFD600] border border-[#FFD600]/20 px-3 py-1.5 rounded-full text-xs font-medium">
                <Sparkles className="w-3.5 h-3.5" />
                <span>#1 Platform for Students</span>
              </motion.div>

              <motion.h1 variants={itemVariants} className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-[1.08] tracking-tight text-[#f4f4f5]">
                Share Code.<br />
                Share Files.<br />
                <span style={{ background: 'linear-gradient(135deg, #FFD600, #FF6A00)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
                  No Login Required.
                </span>
              </motion.h1>

              <motion.p variants={itemVariants} className="text-base sm:text-lg text-[#a1a1aa] max-w-xl leading-relaxed">
                Instantly share code snippets, notes, files, terminal outputs and links with classmates using a simple 6-digit room PIN.
              </motion.p>

              <motion.div variants={itemVariants} className="flex flex-wrap gap-3 mt-2">
                <Link href="/create">
                  <Button variant="yellow" size="lg" className="gap-2 group shadow-[0_0_20px_rgba(255,214,0,0.25)] hover:shadow-[0_0_30px_rgba(255,214,0,0.35)]">
                    <span>Create Room</span>
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                  </Button>
                </Link>
                <Link href="/join">
                  <Button variant="outline" size="lg">Join Room</Button>
                </Link>
              </motion.div>

              <motion.div variants={itemVariants} className="flex items-center gap-2 mt-2">
                <div className="inline-flex items-center gap-1.5 bg-[#FFD600]/10 text-[#FFD600] border border-[#FFD600]/20 px-3 py-1.5 rounded-full text-xs font-medium">
                  <Lock className="w-3 h-3" />
                  No login. No tracking. Just a PIN.
                </div>
              </motion.div>
            </motion.div>
          </div>

          {/* Right Column — Animated PIN Hero */}
          <div className="lg:col-span-5 flex justify-center relative">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ type: 'spring', stiffness: 80, delay: 0.3 }}
              className="relative w-full max-w-[420px] aspect-square flex items-center justify-center"
            >
              {/* Decorative ring */}
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[320px] h-[320px] rounded-full border border-dashed border-white/[0.07] animate-spin" style={{ animationDuration: '60s' }} />
              <div className="absolute -bottom-4 -right-4 w-32 h-32 rounded-full" style={{ background: 'radial-gradient(circle, rgba(255,214,0,0.12), transparent 70%)' }} />
              <div className="absolute -top-6 -left-6 w-16 h-16 rounded-xl border border-[#4F7CFF]/20 bg-[#4F7CFF]/5" />

              <div className="relative z-10 w-full flex flex-col gap-6 items-center">
                {/* Upper cards */}
                <div className="flex justify-between w-full px-4 items-end">
                  <Card variant="default" className="p-3 w-32 rotate-[-6deg] hover:rotate-0 transition-transform cursor-pointer">
                    <div className="bg-[#FFD600]/15 p-2 rounded-xl flex items-center justify-center mb-2 border border-[#FFD600]/20">
                      <Code className="w-6 h-6 text-[#FFD600]" />
                    </div>
                    <div className="h-1.5 w-16 bg-white/10 rounded-full mb-1" />
                    <div className="h-1.5 w-12 bg-white/5 rounded-full" />
                  </Card>
                  <Card variant="default" className="p-3 w-28 rotate-[8deg] hover:rotate-0 transition-transform cursor-pointer border-[#FF6A00]/20">
                    <Folder className="w-10 h-10 text-[#FF6A00] mb-1" />
                    <div className="h-1.5 w-10 bg-white/10 rounded-full" />
                  </Card>
                </div>

                {/* PIN digits */}
                <div className="flex flex-col items-center gap-2">
                  <span className="text-xs text-[#71717a] uppercase tracking-widest font-medium">Room PIN</span>
                  <div className="flex gap-1.5">
                    {pinDigits.map((digit, idx) => (
                      <RollingDigit key={idx} value={digit} baseAngle={(idx - 2.5) * 3} />
                    ))}
                  </div>
                </div>

                {/* Lower cards */}
                <div className="flex justify-between w-full px-4 items-start">
                  <Card variant="default" className="p-3 w-28 rotate-[-12deg] hover:rotate-0 transition-transform cursor-pointer border-[#8B5CF6]/20">
                    <FileText className="w-8 h-8 text-[#8B5CF6] mb-2" />
                    <div className="h-1.5 w-12 bg-white/10 rounded-full mb-1" />
                    <div className="h-1.5 w-8 bg-white/5 rounded-full" />
                  </Card>
                  <Card variant="default" className="p-3 w-32 rotate-[6deg] hover:rotate-0 transition-transform cursor-pointer border-[#22C55E]/20">
                    <div className="bg-[#22C55E]/15 border border-[#22C55E]/20 h-12 rounded-xl flex items-center justify-center mb-1 text-[#22C55E] text-xs font-bold">
                      ACTIVE
                    </div>
                    <div className="h-2 w-14 bg-white/10 rounded-full" />
                  </Card>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* ── Features Section (Agent Bento Grid) ── */}
        <section id="features" className="flex flex-col gap-12 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="inline-flex items-center gap-1.5 bg-[#FF6A00]/10 text-[#FF6A00] border border-[#FF6A00]/20 px-3 py-1.5 rounded-full text-xs font-medium">
              <Zap className="w-3.5 h-3.5" />
              Platform Capabilities
            </span>
            <h2 className="text-2xl sm:text-4xl font-bold text-[#f4f4f5] max-w-2xl leading-tight">
              Features Packed for Classrooms
            </h2>
            <p className="text-sm text-[#71717a] max-w-md leading-relaxed">
              Everything you and your classmates need to share files, code snippets, notes, and chats instantly in a secure room.
            </p>
          </div>

          {/* Bento Grid */}
          <div className="gsap-feature-grid grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {featureItems.map((item, idx) => (
              <div key={idx} className="gsap-feature-card">
                <div
                  className="glow-card p-5 h-full flex flex-col gap-4 text-left group transition-all duration-300 cursor-pointer"
                  style={{ '--glow-color': item.accent } as React.CSSProperties}
                >
                  <div className="flex justify-between items-start">
                    <div
                      className="w-10 h-10 rounded-xl flex items-center justify-center"
                      style={{ background: `${item.accent}15`, border: `1px solid ${item.accent}25`, color: item.accent }}
                    >
                      {item.icon}
                    </div>
                    <span
                      className="text-[10px] font-medium px-2 py-0.5 rounded-full border"
                      style={{ color: item.accent, borderColor: `${item.accent}25`, background: `${item.accent}10` }}
                    >
                      {item.badge}
                    </span>
                  </div>
                  <h3 className="text-sm font-semibold text-[#f4f4f5]">{item.title}</h3>
                  <p className="text-xs text-[#71717a] leading-relaxed">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── How It Works ── */}
        <section id="how-it-works" className="flex flex-col gap-12 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="inline-flex items-center gap-1.5 bg-[#4F7CFF]/10 text-[#4F7CFF] border border-[#4F7CFF]/20 px-3 py-1.5 rounded-full text-xs font-medium">
              <BookOpen className="w-3.5 h-3.5" />
              System Guide
            </span>
            <h2 className="text-2xl sm:text-4xl font-bold text-[#f4f4f5] max-w-2xl leading-tight">
              How Lab Buddies Works
            </h2>
            <p className="text-sm text-[#71717a] max-w-md leading-relaxed">
              A secure, zero-friction path to temporary student collaborations in 4 simple steps.
            </p>
          </div>

          <div className="flex flex-col gap-4 max-w-4xl mx-auto w-full">
            {steps.map((step, idx) => (
              <div key={idx} className="gsap-step-card">
                <div className="glass-card p-5 md:p-6 hover:border-white/15 transition-all">
                  <div className="flex flex-col md:flex-row gap-5 items-start md:items-center">
                    <div
                      className="w-12 h-12 rounded-2xl flex items-center justify-center font-bold text-lg flex-shrink-0"
                      style={{ background: `${step.accent}15`, border: `1px solid ${step.accent}25`, color: step.accent }}
                    >
                      {step.number}
                    </div>
                    <div className="flex-1 flex flex-col gap-1.5 text-left">
                      <h3 className="text-sm font-semibold text-[#f4f4f5] flex items-center gap-2">
                        <span style={{ color: step.accent }}>{step.icon}</span>
                        {step.title}
                      </h3>
                      <p className="text-xs text-[#71717a] leading-relaxed">{step.description}</p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── About Section ── */}
        <section id="about" className="flex flex-col gap-12 scroll-mt-20">
          <div className="flex flex-col gap-3 items-center text-center">
            <span className="inline-flex items-center gap-1.5 bg-[#8B5CF6]/10 text-[#8B5CF6] border border-[#8B5CF6]/20 px-3 py-1.5 rounded-full text-xs font-medium">
              <Target className="w-3.5 h-3.5" />
              Our Mission
            </span>
            <h2 className="text-2xl sm:text-4xl font-bold text-[#f4f4f5] max-w-2xl leading-tight">
              Designed to Connect Classmates
            </h2>
            <p className="text-sm text-[#71717a] max-w-md leading-relaxed">
              We believe study resources should be shared instantly, privately, and seamlessly.
            </p>
          </div>

          <div className="flex flex-col gap-6 max-w-4xl mx-auto w-full">
            {/* Story Card */}
            <div className="gsap-about-story">
              <div className="glass-card p-6 md:p-8 text-left flex flex-col gap-4">
                <div className="flex items-center gap-2 border-b border-white/[0.06] pb-3">
                  <BookOpen className="w-4 h-4 text-[#FF6A00]" />
                  <h3 className="text-sm font-semibold text-[#f4f4f5]">The Story behind "Lab Buddies"</h3>
                </div>
                <div className="flex flex-col gap-3 text-sm text-[#71717a] leading-relaxed">
                  <p>During computer lab lectures and group study sessions, sharing code scripts, PDF slides, and terminal stack outputs was incredibly frustrating. Emailing files felt archaic, setting up GitHub repos for simple debugging code took too much time, and using common messaging boards leaked personal emails or phone numbers.</p>
                  <p>We designed <span className="text-[#f4f4f5] font-medium">Lab Buddies</span> to solve this exact bottleneck. It is a lightweight, zero-configuration study room workspace where anyone can launch a collaboration session under a 6-digit PIN.</p>
                  <p>By combining instant chat messaging and shared sticky notes with file sharing and code helpers, we created the ultimate lightweight study room for students.</p>
                </div>
              </div>
            </div>

            {/* Values Grid */}
            <div className="gsap-about-values-grid grid grid-cols-1 md:grid-cols-3 gap-4 text-left">
              {values.map((val, idx) => (
                <div key={idx} className="gsap-about-value">
                  <div
                    className="glow-card p-5 h-full flex flex-col gap-3"
                  >
                    <div
                      className="w-10 h-10 rounded-xl flex items-center justify-center"
                      style={{ background: `${val.accent}15`, border: `1px solid ${val.accent}25`, color: val.accent }}
                    >
                      {val.icon}
                    </div>
                    <h4 className="text-sm font-semibold text-[#f4f4f5]">{val.title}</h4>
                    <p className="text-xs text-[#71717a] leading-relaxed">{val.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── SEO FAQ Section (High-Intent Competitor & Alternative Searches) ── */}
        <section id="faq" className="flex flex-col gap-10 max-w-4xl mx-auto w-full text-left">
          <div className="flex flex-col gap-2">
            <span className="text-xs uppercase tracking-wider text-[#FFD600] font-semibold">Frequently Asked Questions</span>
            <h2 className="text-2xl sm:text-3xl font-black text-[#f4f4f5] tracking-tight">
              Everything You Need to Know About Lab Buddies
            </h2>
            <p className="text-xs sm:text-sm text-[#71717a]">
              Fast answers to common questions about cross-device file sharing, anonymous study rooms, and alternatives.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            {[
              {
                q: "How does Lab Buddies compare to Snapdrop and Sharedrop?",
                a: "Unlike Snapdrop and Sharedrop which strictly require both devices to be on the exact same Wi-Fi subnet (failing frequently on university campus networks, mobile hotspots, and VPNs), Lab Buddies connects devices instantly using a simple 6-digit Room PIN across any network or cellular connection, while adding real-time code snippet formatting, collaborative sticky notes, and WhatsApp-style chat."
              },
              {
                q: "Can I share files between Android, iPhone, Windows, Mac, and Linux?",
                a: "Yes! Lab Buddies is 100% browser-based and works seamlessly as a Progressive Web App (PWA) across all modern operating systems and web browsers without downloading any third-party software or browser extensions."
              },
              {
                q: "Is there any signup, login, or personal info required?",
                a: "No. Lab Buddies requires zero logins, no emails, and no phone numbers. You can launch a workspace or join an existing study room in two clicks using just a 6-digit Room PIN."
              },
              {
                q: "How does the auto-delete self-destruct timer protect my files and notes?",
                a: "Every room has a configured self-destruct countdown timer (from 5 minutes up to 24 hours). Once the countdown expires, all shared files, code snippets, notes, and chat logs are permanently purged from the servers."
              },
              {
                q: "Is Lab Buddies completely free to use?",
                a: "Yes! Lab Buddies is 100% free for students and developers to create temporary collaboration workspaces, transfer files, run lab attendance, and share formatted code snippets."
              }
            ].map((faq, index) => (
              <details key={index} className="group border border-white/[0.08] bg-[#0f0f10] rounded-2xl p-5 open:bg-white/[0.03] transition-all cursor-pointer">
                <summary className="font-bold text-sm text-[#f4f4f5] flex items-center justify-between list-none select-none">
                  <span>{faq.q}</span>
                  <span className="text-[#FFD600] font-mono text-lg transition-transform duration-200 group-open:rotate-45">+</span>
                </summary>
                <p className="text-xs text-[#a1a1aa] leading-relaxed mt-3 pt-3 border-t border-white/[0.06]">
                  {faq.a}
                </p>
              </details>
            ))}
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/[0.06] py-6 mt-auto select-none bg-[#050608]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-[#71717a]">
          <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-6">
            <span className="text-[#a1a1aa]">No Signups. No Downloads. Just Share.</span>
            <span className="hidden sm:inline text-white/10">|</span>
            <div className="flex gap-4">
              <Link href="/privacy" className="hover:text-[#f4f4f5] transition-colors">Privacy Policy</Link>
              <Link href="/terms" className="hover:text-[#f4f4f5] transition-colors">Terms of Service</Link>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-[10px] text-white/30">Powered by</span>
            <a
              href="https://modistudio.online"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 bg-white/[0.05] border border-white/[0.08] text-white/70 hover:text-white hover:bg-white/[0.08] rounded-full pl-1 pr-3 py-1 transition-all"
            >
              <Image src="/modi-studio-logo.jpg" alt="Modi Studio logo" width={20} height={20} className="w-5 h-5 rounded-full object-cover" />
              <span className="text-[10px] font-medium tracking-wide">Modi Studio</span>
            </a>
          </div>

          <div className="flex items-center gap-1.5 text-[#22C55E]">
            <Shield className="w-3.5 h-3.5" />
            <span>100% Private</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
